const assert = require('node:assert/strict');
const path = require('node:path');
const createEngine = require(path.resolve(process.argv[2]));
(async () => {
  const lines = [];
  const engine = await createEngine({ print: line => lines.push(line) });
  const send = line => engine.ccall('uci_command', null, ['string'], [line], { async: true });
  await send('uci');
  assert(lines.includes('uciok'));
  assert(lines.some(line => line.includes('name DeltaPruning')));
  await send('isready');
  assert.equal(lines.at(-1), 'readyok');
  await send('position startpos moves e2e4');
  await send('go depth 2');
  assert.match(lines.at(-1), /^bestmove [a-h][1-8][a-h][1-8][qrbn]?$/);
  assert(lines.some(line => line.startsWith('info depth 2 ')));
  await send('position startpos moves e2e5');
  assert(lines.at(-1).startsWith('info string error:'));
  await send('position fen 7k/6Q1/6K1/8/8/8/8/8 b - - 0 1');
  await send('go depth 1');
  assert.equal(lines.at(-1), 'bestmove 0000');
  await send('position fen 5b1k/8/8/3pP3/4K3/8/8/8 w - d6 0 1 moves e5d6');
  await send('isready');
  assert.equal(lines.at(-1), 'readyok');
  await send('ucinewgame');
  await send('position startpos');
  const before = lines.length;
  const start = Date.now();
  const searching = send('go infinite');
  await new Promise(resolve => setTimeout(resolve, 50));
  engine.ccall('uci_command', null, ['string'], ['isready']);
  assert.equal(lines.at(-1), 'readyok');
  assert(!lines.slice(before).some(line => line.startsWith('bestmove ')));
  engine.ccall('uci_command', null, ['string'], ['stop']);
  await searching;
  assert(Date.now() - start < 3000, 'stop must interrupt a running search');
  assert.equal(lines.slice(before).filter(line => line.startsWith('bestmove ')).length, 1);
  console.log('WebAssembly UCI checks passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
